### ISSUE TITLE
Enable automatic test runs on commit

### ISSUE THREAD

**Issue by fluffynuts** [apache/logging-log4net#106]
It would be highly beneficial to the project to have automatic test runs (`npm test`) for every commit. To this end, a GitHub action that (eventually) invokes `npm test` would be fantastic.

**Comment by ppkarwasz** [comment]
@fluffynuts,

I tried to add an NPM-based test run as you suggested in: https://github.com/apache/logging-log4net/blob/master/.github/workflows/build.yaml

However this fails on Ubuntu and MacOS (see [run 10825983032](https://github.com/apache/logging-log4net/actions/runs/10825982032), whereas the dotnet-based [run 10825714954](https://github.com/apache/logging-log4net/actions/runs/10825714954) doesn't. Could you look into that?

**Comment by ppkarwasz** [comment]
@fluffynuts, the logs are available in the two runs I cited before:

- [run 10825983032](https://github.com/apache/logging-log4net/actions/runs/10825982032)
- [run 10825714954](https://github.com/apache/logging-log4net/actions/runs/10825714954)

I don't know which logs are relevant, so I didn't include any.

**Comment by gdziadkiewicz** [comment]
@ppkarwasz @fluffynuts, are you still working on that? If not, can I try to make it work?

**Comment by FreeAndNil** [comment]
@gdziadkiewicz you can try.
Piotr and Davyd don't have enough time.

**Comment by ppkarwasz** [comment]
@gdziadkiewicz,

As Jan said, go ahead, we are swamped with other tasks.
IIRC Jan said that the Log4Net version does not need NPM, so maybe the workflow should just use `dotnet`.

**Comment by fluffynuts** [comment]
I'd suggest using npm though - `zarro` does "all the right things" by convention when testing dotnet projects. `npm test` should _just work everywhere_.
