### ISSUE TITLE
Dropping support for older runtimes

### ISSUE THREAD

**Issue by fluffynuts** [apache/logging-log4net#111]
Log4net supports a lot of really old runtimes, including net2.0 and net3.5 _CE_ (Compact Edition) which can be notoriously difficult to install on windows (I've been lucky and unlucky - today, it "just worked" without intervention, but previously, I've crafted the included powershell scripts to install .net framework 3.5.

These targets make it impossible (as far as I know, and I've tried) to build on non-windows hosts. However, if we could reduce the targeted runtime list to:
- net462
- netstandard2.0

then we could support all supported versions of .net (at time of writing, the lowest supported netfx version is 4.6.2) because we can use Mono on non-windows hosts to provide the api to compile system functionality against (see [MonoForFramework.targets](https://github.com/apache/logging-log4net/blob/master/src/MonoForFramework.targets))

Apart from quicker builds & testing times, this would be highly beneficial in that it would make contributing to log4net much easier.

On one hand, I'd really like to maintain as much compatibility as possible, but on the other, I'd like to remove hurdles for prospective devs (and myself 😅 )

**Comment by FreeAndNil** [comment]
+1 from me.
I think supporting net462 & netstandard2.0 is enough for everyone who is able and willing to upgrade their depencies to newer versions.

**Comment by fluffynuts** [comment]
I think if we do this, it's probably a good idea to do a major version bump, so that no-one requiring an older version would accidentally install a newer one with what they believe to be a small upgrade; I did the same thing with my libraries when I dropped support for .net 4.5.2

**Comment by gitkrasty** [comment]
Is multitargeting at least to the latest supported .NET runtimes still an option?

**Comment by fluffynuts** [comment]
I would still want to maintain a net462 package (and whatever comes after that in NETFX-world's support matrix - right now, that's the lowest version of .net framework that is supported by Microsoft)

Technically, you _can_ use netstandard packages from net462 hosts, but doing so adds a bunch of overhead for the host as the entire netstandard runtime has to be shimmed out - go ahead and try it, you'll see a ton of compatibility packages coming down. And there's no benefit from our side in dropping netfx as we can stub out the netfx api (4.6.2+) from Mono when building on linux (reminder: this doesn't mean the output is linked to Mono, it just means that during build, the compiler is able to find runtime apis from Mono, to pass the build, and later externs them)

The versions I'd like to drop support for are:
- net20
- net35
- net40
- net40-client
- net45

These can be a mission to get working, even on a windows host - I've had times when I could just install and use, and other times where I literally fought for ages and gave up, and it just so happened I could do so after a complete OS refresh. And they're _never_ going to work on non-windows hosts, so expecting contributions from people running other platforms is fantasy - people can't effectively contribute if they can't even build the project ):

**Comment by fluffynuts** [comment]
btw targeting netstandard & .net 4.6.2 is trivial with the Mono shim - it's how I do all my personal packages where I expect them to be used on netfx, eg NExpect, PeanutButter.*.
