### ISSUE TITLE
Thread prints generic thread name instead of ID ".NET TP Worker"

### ISSUE THREAD

**Issue by Alhalwachi-BBK** [apache/logging-log4net#112]
After upgrading to ASP.NET core 8, the logs using the property %thread print a generic thread name instead of the thread ID.

The commit https://github.com/apache/logging-log4net/commit/ab74a0a3c0d90e8736bff29fca74e858947c0d24 seems to be related to a fix for the issue. Is there any timeline/date for when this will be release?

**Comment by FreeAndNil** [comment]
Yes, this issue was fixed by #103.
A release is planned, but there is no date yet.
