### ISSUE TITLE
NullRefException from shutdown in 2.0.16

### ISSUE THREAD

**Issue by erikmav** [apache/logging-log4net#118]
[This commit](https://github.com/apache/logging-log4net/commit/b2ef9f6ced9d755844f13586f189a814e20c0c91) introduced after 2.0.15 results in an NRE during some shutdown cases where m_lockingModel is null during Close/Dispose.

The simplistic fix is to add a check to FileAppender. The better fix is to enable nullability on FileAppender, RollingFileAppender, and their unit tests, and fix all nullability problems.

A fix is needed as a 2.0.17 package in addition to the proposed 3.0 package.

**Comment by erikmav** [comment]
@FreeAndNil

**Comment by FreeAndNil** [comment]
Thanks for reporting.
I will take a look.

**Comment by erikmav** [comment]
I'm putting together a large PR with the nullability setting change. It's a lot to review so for faster release it's probably better to fix the dispose case as a quick fix then ship 2.0.17.

**Comment by FreeAndNil** [comment]
@erikmav I agree. Please rebase/start your nullability PR on Feature/111-Dropping-support-for-older-runtimes.
Will you provide the quick fix or should I do?

**Comment by erikmav** [comment]
Can you add the quick fix? I'm heads-down on the large PR.

**Comment by erikmav** [comment]
@FreeAndNil Small and large PRs posted.

**Comment by FreeAndNil** [comment]
Will be fixed in 2.0.17 (2024-03-22).

**Comment by andreycha** [comment]
Hi @FreeAndNil any ETA when 2.0.17 stable version is going to be released? I need some changed from 2.0.16 but don't want to upgrade without this hotfix.

**Comment by FreeAndNil** [comment]
@andreycha definitely next week.

**Comment by FreeAndNil** [comment]
@andreycha
https://github.com/apache/logging-log4net/releases/tag/rel%2F2.0.17
https://www.nuget.org/packages/log4net/2.0.17

**Comment by andreycha** [comment]
@FreeAndNil thanks a lot!
