### ISSUE TITLE
Most links in the documentation are broken

### ISSUE THREAD

**Issue by marcel-landman** [apache/logging-log4net#130]
This is where we are told the documentation is:
https://logging.apache.org/log4net/

All the top level links work, but as soon as you click through to a second level, the link is broken e.g.
https://logging.apache.org/log4net/release/sdk/index.html

**Comment by FreeAndNil** [comment]
@marcel-landman thanks for reporting.
I discovered the same yesterday 😉.
A fix (https://github.com/apache/logging-log4net/pull/121/commits/61e28326da40646161fe5167905f6c5f55e468a2) is under way and will be deployed next week (#121).
