### ISSUE TITLE
3.0.0-preview.1

### ISSUE THREAD

**Issue by FreeAndNil** [apache/logging-log4net#139]
Issue for preparing the first preview of 3.0.0

**Comment by FreeAndNil** [comment]
## Breaking Changes
### Framework Support
**Attention:** Starting with 3.0.0 we only support the following target frameworks
- net462
- netstandard2.0

The reasoning for this change can be found in #111

### Deleted obsolete API (#125)
- obsolete since 1.2.14 - 2015
  - `log4net.Appender.BufferingAppenderSkeleton.OnlyFixPartialEventData`
  - `log4net.Appender.ColoredConsoleAppender.ctor(ILayout)`
  - `log4net.Appender.ColoredConsoleAppender.ctor(ILayout, bool)`
  - `log4net.Appender.ConsoleAppender.ctor(ILayout)`
  - `log4net.Appender.ConsoleAppender.ctor(ILayout, bool)`
  - `log4net.Appender.DebugAppender.ctor(ILayout)`
  - `log4net.Appender.EventLogAppender.ctor(ILayout)`
  - `log4net.Appender.FileAppender.ctor(ILayout, string)`
  - `log4net.Appender.FileAppender.ctor(ILayout, string, bool)`
  - `log4net.Appender.MemoryAppender.OnlyFixPartialEventData`
  - `log4net.Appender.SmtpAppender.LocationInfo`
  - `log4net.Appender.TextWriterAppender.ctor(ILayout, Stream)`
  - `log4net.Appender.TextWriterAppender.ctor(ILayout, TextWriter)`
  - `log4net.Appender.TraceAppender.ctor(ILayout)`
  - `log4net.Config.DOMConfigurator`
  - `log4net.Config.AliasDomainAttribute`
  - `log4net.Config.DomainAttribute`
  - `log4net.Config.DOMConfiguratorAttribute`
  - `log4net.Core.LoggerManager.GetLoggerRepository`
  - `log4net.Core.LoggerManager.CreateDomain`
  - `log4net.Core.LoggingEventData.TimeStamp`
  - `log4net.Core.LoggingEvent.GetExceptionStrRep`
  - `log4net.Core.LoggingEvent.FixVolatileData`
  - `log4net.LogManager.GetLoggerRepository`
  - `log4net.LogManager.CreateDomain`
- obsolete since 2.0.6 - 2016
  - `log4net.Util.SystemInfo.ProcessStartTime`

### Other changes (#124)
- `log4net.Config.AliasRepositoryAttribute` is now sealed
- `log4net.Config.RepositoryAttribute` is now sealed
- `log4net.Config.XmlConfiguratorAttribute` is now sealed
- interface `log4net.Appender.AppenderCollection.IAppenderCollectionEnumerator` is now obsolete and must be replaced by `IEnumerator<IAppender>`
- `log4net.Appender.MemoryAppender.m_eventsList` (protected field) was changed from `ArrayList` to `List<LoggingEvent>` 
  - for getting `m_eventsList.SyncRoot` you need to cast it: `((ICollection)m_eventsList).SyncRoot`

## Enhancements
- #111 (by @fluffynuts and @freeandnil)
- #124 (by @erikmav)
- #125 (by @erikmav)
- #127 (by @freeandnil)

**Comment by FreeAndNil** [comment]
@erikmav Can you test 3.0.0-preview.2 on your side?

**Comment by erikmav** [comment]
Preview.1 and preview.2 both checked out on 2 services I run. Thanks for publishing - looking forward to the final release.
________________________________
