### ISSUE TITLE
Use Logging Services common pages

### ISSUE THREAD

**Issue by vy** [apache/logging-log4net#144]
I have revamped the [Download](https://logging.apache.org/download.html), [Support](https://logging.apache.org/support.html), and [Security](https://logging.apache.org/security.html) pages of Logging Services (LS) such that they now cover all LS projects. In the Log4j website, I have wired all associated links to there and I have replaced all overlapping content to point to there. Would you consider implementing the following changes for the left menu of the Log4net website?
1. Point _"Download"_ to the LS Download page
1. Remove the _"Security Reports"_
1. Point the _"Security"_ in the left menu to the LS Security page
1. Replace _"Mailing Lists"_, _"Issue Tracking"_ links with a _"Support"_ link pointing to the LS Support page

**Comment by LaurentDardenne** [comment]
Does this page ( https://downloads.apache.org/logging/log4net/)  need to be updated? 

![image](https://github.com/apache/logging-log4net/assets/4894452/86190a0c-275d-4c89-922f-dffd97794919)

**Comment by FreeAndNil** [comment]
@LaurentDardenne you are right.
@vy Can you please remove https://dist.apache.org/repos/dist/release/logging/log4net/README.html ?

**Comment by FreeAndNil** [comment]
@vy I've created #145, please review.

**Comment by vy** [comment]
@FreeAndNil @LaurentDardenne Removed `README.html` and `KEYS` symlink from the https://dist.apache.org/repos/dist/dev/logging/log4net Subversion folder.

https://archive.apache.org/dist/logging/log4net is a (bandwidth-throttled!) HTTP mirror of the Subversion folder (for ASF's legal archiving purposes) and https://downloads.apache.org/logging/log4net is a download-friendly subset of the former containing only the most recent releases.
