### ISSUE TITLE
Add an `Installation` page and rework the `Download` page

### ISSUE THREAD

**Issue by vy** [apache/logging-log4net#146]
_[**Disclaimer:** I am not a .NET developer. Apologies in advance if I say something nonsense.]_

Currently, in the Log4Net website, I am not able to quickly answer the following questions:

* Is Log4Net available in NuGet? If so, what are its package coordinates?
* How can I quickly write a .NET application using Log4Net NuGet packages?

I suggest to update the current website as follows:

* Create an `Installation` page addressing the above questions to quickly get users started
* Create a `Download` page (currently the `Download` link in the left menu points to the Logging Services Download page), similar to [the one Log4j has](https://logging.staged.apache.org/log4j/2.x/download.html), containing two bullets:
  * _"Do you want to install Log4Net in your .NET application? See the Installation page."_
  * "_Do you want to manually download the artifacts? See the Logging Services download page."_

**Comment by FreeAndNil** [comment]
Closed by #148
