### ISSUE TITLE
Projects page link to downloads produces error 404

### ISSUE THREAD

**Issue by dpsenner** [apache/logging-log4net#152]
The following site contains a link to downloads:

https://projects.apache.org/project.html?logging-log4net

That points to:

https://logging.apache.org/log4net/download.html

Which does no longer exist, probably because moved to (or a redirect has been removed):

https://logging.apache.org/log4net/release/download.html

The initial projects page appears to be generated from DOAP files.

**Comment by FreeAndNil** [comment]
@dpsenner thanks for reporting. I will fix it when I'm back from vacation.

**Comment by FreeAndNil** [comment]
@dpsenner I've updated the DOAP-file.

**Comment by ppkarwasz** [comment]
Maybe we should point users directly to https://logging.apache.org/download.html?

**Comment by FreeAndNil** [comment]
@ppkarwasz Thanks. I've updated the DOAP-file (again).
