### ISSUE TITLE
Configuration System Initialization Failure with PublishTrimmed in .NET 8

### ISSUE THREAD

**Issue by tmoonlight** [apache/logging-log4net#165]
Hi,

I am using log4net in my project running on .NET 8. When I enable the “PublishTrimmed” setting in my project file (< PublishTrimmed >true< /PublishTrimmed >), I consistently receive the following errors during the configuration of log4net:

```

Starting up as a console service host
Service NSPServer started
The NSPServer service is now running, press Control+C to exit.
Another instance of the program is running. It may cause fatal error.
Initializing..
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.MissingMethodException: Cannot dynamically create an instance of type 'System.Configuration.ClientConfigurationHost'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Configuration.TypeUtil.CreateInstance(Type)
   at System.Configuration.Internal.ConfigSystem.System.Configuration.Internal.IConfigSystem.Init(Type, Object[] )
   at System.Configuration.ClientConfigurationSystem..ctor()
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String)
``` 

This issue persists even when I configure log4net purely through code, without using a log4net.config file. The problem does not occur in non-trimmed mode or older versions of the trimming mode (such as .NET Core 3.0).

To assist in diagnosing this issue, I have attached a file containing my program that can reliably reproduce the problem:
https://github.com/tmoonlight/NSmartProxy/releases/download/v1.4.0/nspclient_scd_win_x86_v1.4.0.zip

**Comment by FreeAndNil** [comment]
related to #147 
related to #142

**Comment by FreeAndNil** [comment]
@tmoonlight can you check whether #166 fixes your problem?

**Comment by tmoonlight** [comment]
I have followed your method, but the issue with the PublishTrimmed program still persists.
![image](https://github.com/user-attachments/assets/1873fb7e-93c1-4009-847f-3a73e8f89573)

**Comment by tmoonlight** [comment]
Hi,
The issue seems to be more complex than initially thought. I found that not only is log4net affected, but other parts of the code also encounter problems when trimming. For example, embedded strings and resources in my project are no longer accessible. I will try downgrading my .NET Core version and attempt packaging again.
Thank you for your support:)

**Comment by FreeAndNil** [comment]
No problem - as you can see in #142 and #147 you are not the only one with those problems using aot.
Feel free to reopen when you get new details.

**Comment by hhxdestiny** [comment]
The problem still exists on 3.0.1

**Comment by FreeAndNil** [comment]
@hhxdestiny nobody said otherwise.
In case you have a sample application which reproduces the problem, feel free to reopen (or create a new issue).
