### ISSUE TITLE
RollingFileAppender opens up more basic methods for extension to improve scalabilityexten

### ISSUE THREAD

**Issue by RunWangusst** [apache/logging-log4net#167]
I want to customize my roll files name, currently roll file names will rename to origin file name of with suffix .1 .2 .3 and so on. So my log files will like this: **log.txt.1**   **log.txt.2** ...
However, it will change the suffix of a txt file, so i can not open it with my notepad++ by default. Instead i want to add the number identifier before file suffix , such as  **log_1.txt** ,  **log_2.txt** .... **log_n.txt**. 
So i would like to override GetNextOutputFileName(string fileName) method to satisify my requirements, however, it does not support override.

Maybe you can open GetNextOutputFileName or other methods for override to support this kind of requirements.

**Comment by FreeAndNil** [comment]
Hi @RunWangusst,

have you tried using PreserveLogFileNameExtension?

```
    <appender name="LogFileAppender" type="log4net.Appender.RollingFileAppender">
      ...
      <param name="PreserveLogFileNameExtension" value="true"/>
    </appender>
```

**Comment by FreeAndNil** [comment]
@RunWangusst is this still relevant for you?
