### ISSUE TITLE
ColoredConsoleAppender writes UTF-8 preamble to the console on initialization

### ISSUE THREAD

**Issue by RoboBurned** [apache/logging-log4net#168]
I have an issue with ColoredConsoleAppender on WIndows 10.
After initialization it prints an extra "space" to the console at the very beginning.
It writes the preamble of UTF-8 encoding that results in a visual "space" in windows console.

After debugging I found that it happens in ActivateOptions function when setting `AutoFlush` property of StreamWriter to true.
https://github.com/apache/logging-log4net/blob/ad0180f9bfb712cd52bda28b74ec7d64ea7f3bb8/src/log4net/Appender/ColoredConsoleAppender.cs#L467

If you look at sources of Console.WriteLine method, they set `HaveWrittenPreamble` property to `true` to bypass writing it by streamwriter. That's why they have no such issue.
https://referencesource.microsoft.com/#mscorlib/system/console.cs,373

**Comment by FreeAndNil** [comment]
Hi @RoboBurned ,

can you check whether [log4net.3.0.0-preview.2b.zip](https://github.com/user-attachments/files/16626488/log4net.3.0.0-preview.2b.zip) fixes your problem?

**Comment by RoboBurned** [comment]
@FreeAndNil  Yes, the version you provided fixes the issue for me. Thank you.

**Comment by FreeAndNil** [comment]
@RoboBurned Thanks for testing, will be fixed in 3.0.0-Preview.3.
