### ISSUE TITLE
Support converting '.NET Long Running Task' to the numeric thread ID on .NET 8

### ISSUE THREAD

**Issue by Audela-220** [apache/logging-log4net#177]
After upgrading to .NET 8 from .NET framework 4.7.2, the logs using the property %thread print a generic thread name (.NET Long Running Task) instead of the thread ID.

Reference issue: [".NET TP Worker"](https://github.com/apache/logging-log4net/issues/112)

**Comment by FreeAndNil** [comment]
@Audela-220 could you test the issue when we provide a preview version via nuget.org?

**Comment by Audela-220** [comment]
Hello @FreeAndNil 
Sure, please let me know if you prepare a preview version via nuget.org.
Regards

**Comment by FreeAndNil** [comment]
@Audela-220 please test with https://github.com/apache/logging-log4net/releases/tag/rc%2F3.1.0-preview.1
https://www.nuget.org/packages/log4net/3.1.0-preview.1

**Comment by Audela-220** [comment]
@FreeAndNil 
I did it. No problem.
Thank you!!
