### ISSUE TITLE
Log4net V3.0 doesn't log on WPF and WinForm targeting net4.8.0

### ISSUE THREAD

**Issue by fredatgithub** [apache/logging-log4net#192]
I have upgraded Log4net library to v3.0 and no log is created on WPF and WinForm targeting net 4.8.0
In previous version, 2.0.17, it works fine.
I looked at the release notes and I saw that net versions before 4.6.2 were dropped.
Is log4net v3.0 suppose to work for net 4.8.0?
If so do I need to change something in the configuration?

**Comment by FreeAndNil** [comment]
Hi @fredatgithub,

can you please test with 3.0.1?
If that fails, please post your log4net config section quoted by 3 backticks.

**Comment by fredatgithub** [comment]
it works fine with v3.0.1
thanks
