### ISSUE TITLE
Ability to compress rolled files

### ISSUE THREAD

**Issue by FerdinandStapenhorst** [apache/logging-log4net#205]
### Compressing Rolled files in RollingFileAppender
I would like to be able to compress rolled files once thy are created. I don't see any way to get notified if a log file was rolled. Either a Callback or a protected override in the RollingFileAppender class signalling the log file rolling process, so I can interject and do a compression, would be great!

For example, it would be sufficient - I think - to change 
 protected void RollOverRenameFiles(string baseFileName)
to 
 protected virtual void RollOverRenameFiles(string baseFileName)

because then I could create a class 
```
public class CompressingFileAppender : RollingFileAppender
{
  protected virtual void RollOverRenameFiles(string baseFileName)
  {
      // Do the compression stuff here...
  }
}
```

Ferdinand

**Comment by FreeAndNil** [comment]
Hi @FerdinandStapenhorst,

I made the method virtual in #206.

Regards.

Next preview will arrive this week, 3.0.3 probably mid November.

**Comment by FerdinandStapenhorst** [comment]
Thank you so much!

**Comment by FreeAndNil** [comment]
@FerdinandStapenhorst 3.0.3 was released.
https://github.com/apache/logging-log4net/releases/tag/rel/3.0.3
