### ISSUE TITLE
Feature: Implement ArchivingRollingFileAppender - an appender that archives rolled files exceeding maxSizeRollBackups instead of deleting them

### ISSUE THREAD

**Issue by FerdinandStapenhorst** [apache/logging-log4net#207]
I implemented a ArchivingRollingFileAppender class that creates zip archives for all those files that would be deleted once maxSizeRollBackups is reached instead of deleting them.

- Once RollOverRenameFiles() is called, it checks if the maxSizeRollBackups is reached. If so, it compresses the last rolled file and deletes it afterwards
- Once MaximumZipFileSize is reached, it starts rolling the zip files
- It never deletes any of the zip files

Maybe, some time in the future this feature could make it into the log4net standard?

Attached the sources - feel free to use it.

Thanks.

Ferdinand
[ArchivingRollingFileAppender.cs.zip](https://github.com/user-attachments/files/17616653/ArchivingRollingFileAppender.cs.zip)

**Comment by FreeAndNil** [comment]
Thanks. We will keep it in mind in case other users want the same.
