### ISSUE TITLE
Breaking change to FileAppender in a third-digit release

### ISSUE THREAD

**Issue by sketchturner** [apache/logging-log4net#216]
A change to `FileAppender` that breaks backward compatibility was introduced with #196.
`SetQWForFiles` is a publicly visible method that was renamed to `SetQwForFiles`. Need to rename it back in order to keep types that extend `FileAppender` compatible with the latest version of log4net

**Comment by garydgregory** [comment]
I don't think we should keep BC outside of log4-api, but that's just me.

**Comment by FreeAndNil** [comment]
> I don't think we should keep BC outside of log4-api, but that's just me.
@garydgregory log4net is monolithic, we have no separate api (as log4j).

**Comment by FreeAndNil** [comment]
@sketchturner thanks.
Do you need a preview version of log4net?

**Comment by FreeAndNil** [comment]
> By the way, is it by any chance possible to amend the message of the commit that was the result of #217 completion in order to remove the "Co-authored-by" part? Thanks

@sketchturner see https://github.com/apache/logging-log4net/commit/e78f9e3bd6f342e3c35e314c553ab3e3c09fd605

**Comment by sketchturner** [comment]
@FreeAndNil Great. Thank you!
